### ISSUE TITLE
Goey menu

### ISSUE THREAD

**Issue by PEM--** [PEM--/creativepure#3]
http://codepen.io/lbebber/pen/RNgBPP

More Goey: http://tympanus.net/codrops/2015/03/10/creative-gooey-effects/

**Comment by Sivli-Embir** [comment]
:+1:  beautiful

**Comment by PEM--** [comment]
Indeed. I need to do it for understanding the technic used for the 'Goey' stuff.

If you find interesting code snippets, feel free to create issues. We will use it as a kind of roadmap.

**Comment by Sivli-Embir** [comment]
How about those ^_^? I have more but those feel the most reusable, with the context of a CSS framework.

**Comment by PEM--** [comment]
Well, I was thinking of something that would be more classic as we don't know yet how many topics we will need: http://tympanus.net/Development/OffCanvasMenuEffects/elastic.html

**Comment by Sivli-Embir** [comment]
For the demo site nav? That would work nicely, so long each 'element/component' gets its own page with a route. That way it is easy to link to.

**Comment by PEM--** [comment]
A bit too much mobile first. But thinking of it, the desktop menu could morph into it pretty easily. That would be super neat.

**Comment by Sivli-Embir** [comment]
We could try to rework the morph button into a generic morph.

**Comment by Sivli-Embir** [comment]
Also worth throwing out there, my use case is about almost entirely mobile via Cordova. As Crossover is not properly supported in Meteor this means very bad CSS support.

**Comment by PEM--** [comment]
Ouch for Crosswalk! I've been using it last year and it's a killing machine (though a bit complicated to build on a Mac and lots of arguing with the IBM team...). I've seen some guys blogging about it for integrating it with Meteor. They are using it as a Cordova plugin.

Well for the desktop, you will certainly need a landing page. Better get prepared and have a consistent experience that leads the user to the app (and vice-versa) :wink: And actually, the morphing is quite simple to achieve and should give us some good visibility on phablets.

**Comment by PEM--** [comment]
I should be able to create that this WE. For the moment, I'm loosing my sanity on a simple Voronoï diagram...

**Comment by Sivli-Embir** [comment]
Ha ha ha no worries.

**Comment by PEM--** [comment]
Humm... I'm puzzled. I can't get it to work in Meteor. I've created a [Codepen.io](http://codepen.io/PEM--/pen/mJdeNP) and it works.

**Comment by PEM--** [comment]
Done for the Gooey effect... But not convinced after all. It doesn't work on Safari :disappointed: It should be doable with a CSS custom filter. I've never used them on mobile, though.

**Comment by Sivli-Embir** [comment]
Ah hmm... I would assume they would not work on mobile then. Sad, but understandable. Maybe a SVG alt? Though at least for old android SVG support is limited at best.

**Comment by PEM--** [comment]
It's working on Chrome Android. Crosswalk should be able to make it fly. At least for dedicated apps on Android, it should be OK. Well, I've written a warning for thus who would like to use it. Better warn people than seing them disappointed.
